name: "📰 일지"
description: "일지 과정에 대한 보고서입니다"
title: "📰 "
labels: ["📰 일지"]
projects: ["liebespaar93/projects/6"]
assignees:
  - liebespaar93
body:
  - type: input
    id: input_name
    attributes:
      label: 📣 일지 주차
      description: 💭 일지의 주차을 작성해 주세요
      placeholder: 🫧 <주차>
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        # 일지 작성
        일지에 대한 보고서 작성입니다
        ## 업데이트 작성 방법
        - [ ] (#Live 링크)
        - [ ] (#Mission 링크)
        - [ ] 일지 제출
        - [ ] 미션 제출
  - type: checkboxes
    id: checkboxes_list
    attributes:
      label: 📣 작성자 체크리스트
      description: 💭 작성자 체크리스트
      options:
        - label: 🔱 일지 제목을 적절하게 정하였습니까?
          required: false
        - label: 📍 타이틀에 일지 이름을 형식에 맞게 추가하였습니까?
          required: true
        - label: 📌 작성자는 모든 작업에 대한 정보가 공개됨을 동의함니까?
          required: true