name: "📡 라이브"
description: "라이브에 대한 보고서입니다"
title: "📡 "
labels: ["📡 라이브"]
projects: ["liebespaar93/projects/6"]
assignees:
  - liebespaar93
body:
  - type: input
    id: input_name
    attributes:
      label: 📣 라이브 주차
      description: 💭 라이브의 주차을 작성해 주세요
      placeholder: 🫧 <이름>
    validations:
      required: true
  - type: textarea
    id: textarea_description
    attributes:
      label: 📣 라이브 체크
      description: 💭 라이브 수강을 확인합니다.
      placeholder: |
        🫧 <라이브 내용>
        - [ ] 📡 사용자1_n주차
        - [ ] 📡 사용자2_n주차
        - [ ] 📡 사용자3_n주차
        - [ ] 📡 사용자4_n주차
        - [ ] 📡 사용자5_n주차
      render: ''
    validations:
      required: false
  - type: checkboxes
    id: checkboxes_list
    attributes:
      label: 📣 작성자 체크리스트
      description: 💭 작성자 체크리스트
      options:
        - label: 🔱 라이브 제목을 적절하게 정하였습니까?
          required: false
        - label: 📍 타이틀에 라이브 이름을 추가하였습니까?
          required: true
        - label: 📌 작성자는 모든 작업에 대한 정보가 공개됨을 동의함니까?
          required: true